//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMS_SQL
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMS_SQL.IMS_SQL")]
    public interface IMS_SQL
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS_SQL/AddAmount", ReplyAction="http://tempuri.org/IMS_SQL/AddAmountResponse")]
        System.Threading.Tasks.Task<float> AddAmountAsync(string UID, float quotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS_SQL/transferMoney", ReplyAction="http://tempuri.org/IMS_SQL/transferMoneyResponse")]
        System.Threading.Tasks.Task<float> transferMoneyAsync(string username, float quotas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IMS_SQLChannel : ServiceReferenceMS_SQL.IMS_SQL, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class MS_SQLClient : System.ServiceModel.ClientBase<ServiceReferenceMS_SQL.IMS_SQL>, ServiceReferenceMS_SQL.IMS_SQL
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MS_SQLClient() : 
                base(MS_SQLClient.GetDefaultBinding(), MS_SQLClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMS_SQL.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MS_SQLClient(EndpointConfiguration endpointConfiguration) : 
                base(MS_SQLClient.GetBindingForEndpoint(endpointConfiguration), MS_SQLClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MS_SQLClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MS_SQLClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MS_SQLClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MS_SQLClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MS_SQLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<float> AddAmountAsync(string UID, float quotas)
        {
            return base.Channel.AddAmountAsync(UID, quotas);
        }
        
        public System.Threading.Tasks.Task<float> transferMoneyAsync(string username, float quotas)
        {
            return base.Channel.transferMoneyAsync(username, quotas);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMS_SQL))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMS_SQL))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1409/MS_SQL.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MS_SQLClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMS_SQL);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MS_SQLClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMS_SQL);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMS_SQL,
        }
    }
}
